-- MySQL Script generated by MySQL Workbench
-- 03/14/17 11:33:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baglab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `baglab` ;

-- -----------------------------------------------------
-- Schema baglab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baglab` DEFAULT CHARACTER SET utf8 ;
USE `baglab` ;

-- -----------------------------------------------------
-- Table `baglab`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`role` ;

CREATE TABLE IF NOT EXISTS `baglab`.`role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`user_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`user_status` ;

CREATE TABLE IF NOT EXISTS `baglab`.`user_status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`user` ;

CREATE TABLE IF NOT EXISTS `baglab`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `roleId` INT NULL,
  `statusId` INT NULL default 1,
  `user_update` TIMESTAMP,
  `user_create` TIMESTAMP default now(),
  
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_user_role1_idx` (`roleId` ASC),
  INDEX `fk_user_status1_idx` (`statusId` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`roleId`)
    REFERENCES `baglab`.`role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_status1`
    FOREIGN KEY (`statusId`)
    REFERENCES `baglab`.`user_status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baglab`.`bag_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`bag_type` ;

CREATE TABLE IF NOT EXISTS `baglab`.`bag_type` (
  `idbag_type` INT NOT NULL,
  `script` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idbag_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`model` ;

CREATE TABLE IF NOT EXISTS `baglab`.`model` (
  `idModel` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `bag_typeId` INT NOT NULL,
  PRIMARY KEY (`idModel`),
  INDEX `fk_Model_User_idx` (`userId` ASC),
  INDEX `fk_model_bag_type1_idx` (`bag_typeId` ASC),
  CONSTRAINT `fk_Model_User`
    FOREIGN KEY (`userId`)
    REFERENCES `baglab`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_model_bag_type1`
    FOREIGN KEY (`bag_typeId`)
    REFERENCES `baglab`.`bag_type` (`idbag_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baglab`.`order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`order_status` ;

CREATE TABLE IF NOT EXISTS `baglab`.`order_status` (
  `idorder_status` INT NOT NULL auto_increment,
  `code` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idorder_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`order` ;

CREATE TABLE IF NOT EXISTS `baglab`.`order` (
  `idOrder` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `totalPrice` DOUBLE NOT NULL,
  `order_status_idorder_status` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_User1_idx` (`userId` ASC),
  INDEX `fk_order_order_status1_idx` (`order_status_idorder_status` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `baglab`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`order_status_idorder_status`)
    REFERENCES `baglab`.`order_status` (`idorder_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baglab`.`models_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`models_order` ;

CREATE TABLE IF NOT EXISTS `baglab`.`models_order` (
  `modelId` INT(11) NOT NULL,
  `orderId` INT(11) NOT NULL,
  `count` INT(11) NOT NULL,
  PRIMARY KEY (`modelId`, `orderId`),
  INDEX `fk_modelsInOrder_Order1_idx` (`orderId` ASC),
  CONSTRAINT `fk_modelsInOrder_Model1`
    FOREIGN KEY (`modelId`)
    REFERENCES `baglab`.`model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelsInOrder_Order1`
    FOREIGN KEY (`orderId`)
    REFERENCES `baglab`.`order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `baglab`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`material` ;

CREATE TABLE IF NOT EXISTS `baglab`.`material` (
  `idmaterial` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`idmaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`panel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`panel` ;

CREATE TABLE IF NOT EXISTS `baglab`.`panel` (
  `idPanel` INT(11) NOT NULL,
  `picture` MEDIUMBLOB NULL DEFAULT NULL,
  `colourRGB` INT(11) NOT NULL,
  `bag_typeId` INT NOT NULL,
  `materialId` INT NOT NULL,
  PRIMARY KEY (`idPanel`, `bag_typeId`),
  INDEX `fk_panel_bag_type1_idx` (`bag_typeId` ASC),
  INDEX `fk_panel_material1_idx` (`materialId` ASC),
  CONSTRAINT `fk_panel_bag_type1`
    FOREIGN KEY (`bag_typeId`)
    REFERENCES `baglab`.`bag_type` (`idbag_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_panel_material1`
    FOREIGN KEY (`materialId`)
    REFERENCES `baglab`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
