-- MySQL Script generated by MySQL Workbench
-- 03/12/17 20:56:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baglab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baglab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baglab` DEFAULT CHARACTER SET utf8 ;
USE `baglab` ;

-- -----------------------------------------------------
-- Table `baglab`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`User` ;

CREATE TABLE IF NOT EXISTS `baglab`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'active',
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`Config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`Config` ;

CREATE TABLE IF NOT EXISTS `baglab`.`Config` (
  `idConfig` INT NOT NULL AUTO_INCREMENT,
  `configScript` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idConfig`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`Model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`Model` ;

CREATE TABLE IF NOT EXISTS `baglab`.`Model` (
  `idModel` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `configId` INT NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModel`),
  INDEX `fk_Model_User_idx` (`userId` ASC),
  INDEX `fk_Model_Config1_idx` (`configId` ASC),
  CONSTRAINT `fk_Model_User`
    FOREIGN KEY (`userId`)
    REFERENCES `baglab`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Model_Config1`
    FOREIGN KEY (`configId`)
    REFERENCES `baglab`.`Config` (`idConfig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`Order` ;

CREATE TABLE IF NOT EXISTS `baglab`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `totalPrice` DOUBLE NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'processing',
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_User1_idx` (`userId` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `baglab`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`ModelsInOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`ModelsInOrder` ;

CREATE TABLE IF NOT EXISTS `baglab`.`ModelsInOrder` (
  `modelId` INT NOT NULL,
  `orderId` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`modelId`, `orderId`),
  INDEX `fk_modelsInOrder_Order1_idx` (`orderId` ASC),
  CONSTRAINT `fk_modelsInOrder_Model1`
    FOREIGN KEY (`modelId`)
    REFERENCES `baglab`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelsInOrder_Order1`
    FOREIGN KEY (`orderId`)
    REFERENCES `baglab`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baglab`.`Panel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baglab`.`Panel` ;

CREATE TABLE IF NOT EXISTS `baglab`.`Panel` (
  `idPanel` INT NOT NULL,
  `picture` MEDIUMBLOB NULL,
  `colourRGB` INT NOT NULL,
  `configId` INT NOT NULL,
  PRIMARY KEY (`idPanel`, `configId`),
  INDEX `fk_Panel_Config1_idx` (`configId` ASC),
  CONSTRAINT `fk_Panel_Config1`
    FOREIGN KEY (`configId`)
    REFERENCES `baglab`.`Config` (`idConfig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
